services:
  library:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hard-library
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ../Hard-Bot/metadata.json:/usr/share/nginx/html/metadata.json:ro